# Generated by Django 4.0 on 2021-12-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(max_length=100)),
                ('Admin_email', models.CharField(max_length=100, unique=True)),
                ('Admin_contact', models.IntegerField(unique=True)),
            ],
        ),
    ]
